[package]
name = "rust-bignum"
version = "0.0.1"
authors = ["James Sanders <sanderjd@gmail.com>"]

[lib]
name = "bignum"
path = "src/bignum/lib.rs"

[dependencies]
libc = "0.2.31"
rust-gmp = "0.5.0"
num = "0.1.40"
rand = "0.3.16"
